name: CI-testing

on:
  push:
    branches: '**'
  workflow_dispatch:


jobs:
  linting:
    name: Linting and testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install project dependencies
        run: |
          poetry install

      - name: Run ruff
        run: poetry run ruff check

      - name: Run mypy
        run: poetry run mypy .

      - name: Run pylint
        run: poetry run pylint lianapy

      - name: Run pytest
        run: poetry run pytest